{% set name = "log4cxx" %}
{% set version = "1.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_rev: v1.7.0-RC2
  git_url: https://github.com/apache/logging-log4cxx.git
  #url: http://archive.apache.org/dist/logging/{{ name }}/{{ version }}/apache-{{ name }}-{{ version }}.tar.gz
  #sha256: b943ff170393e4ce381ab4c4914396127bf4d44fb8bd1f0e5ef8453f3c4d364c
  patches:
    - patches/fix_fmt_v12.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("log4cxx", max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]
    - zip  # [linux]
    - m2-sed  # [win]
    - m2-zip  # [win]
    - m2-gzip  # [win]
  host:
    - apr
  run:
    - apr
    - libaprutil
    - libapr

test:
  commands:
    - test -f $PREFIX/include/log4cxx/appender.h  # [unix]
    - test -f $PREFIX/include/log4cxx/logmanager.h  # [unix]
    - test -f $PREFIX/lib/liblog4cxx.so  # [linux]
    - test -f $PREFIX/lib/liblog4cxx.dylib  # [osx]
    - if not exist %LIBRARY_INC%\\log4cxx\\log4cxx.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\log4cxx.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\log4cxx.lib exit 1  # [win]

about:
  home: https://logging.apache.org/log4cxx
  license: Apache-2.0
  summary: "Apache Log4cxx is a C++ port of Apache Log4j"
  doc_url: https://logging.apache.org/log4cxx

extra:
  recipe-maintainers:
    - geromka
